Console.Write("What is your first name. >> ");
string F_name = Console.ReadLine() + " ";
Console.Write("What is your last name. >> ");
string L_name = Console.ReadLine() + ".";
Console.WriteLine("It is nice to meet you, " + F_name + L_name);
Console.Write("What shall x be? >> ");
int x = Convert.ToInt32(Console.ReadLine());
Console.Write("What shall y be? >> ");
int y = Convert.ToInt32(Console.ReadLine());
Console.Write("What shall z be? >> ");
int z = Convert.ToInt32(Console.ReadLine());
int a = x + y + z;
Console.Write($"a = {a}");
y -= x;
int b = x * z;
a /= y;
x %= b;
Console.Write($"x = {x}, y = {y}, z = {z}, a = {a}, b = {b}.");